apiVersion: v1
kind: Service
metadata:
  name: '{{ include "bobs.fullname" . }}-svc'
  labels:
    app.kubernetes.io/name: '{{ include "bobs.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: '{{ include "bobs.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
