{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bobs.fullname" . -}}
{{- $routeName := required "config.route_name must be set" .Values.config.route_name -}}
{{- $port := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ $fullName }}'
  labels:
    app.kubernetes.io/name: '{{ include "bobs.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  annotations:
    nginx.org/mergeable-ingress-type: minion
    nginx.org/location-snippets: |
      rewrite ^/{{ $routeName }}-\d+/(.*) /read/$1 break;
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    {{- range $i, $e := until (int $.Values.replicaCount) }}
    - host: {{ printf "%s.%s" $.Values.config.host_prefix $.Values.config.domain | quote }}
      http:
        paths:
          - path: '/{{ $routeName }}-{{ $i }}'
            pathType: Prefix
            backend:
              service:
                name: '{{ $fullName }}-{{ $i }}'
                port:
                  number: {{ $port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
