apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.host }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: {{ .Values.port }}
    port: {{ .Values.port }}

  selector:
    app: minio