apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "polytope-server.fullname" . }}-config'
  labels:
    helm.sh/chart: '{{ include "polytope-server.chart" . }}'
    app.kubernetes.io/name: '{{ include "polytope-server.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
data:
  config.yaml: |
    server:
      host: {{ .Values.bitsConfig.server.host | default "0.0.0.0" | quote }}
      port: {{ .Values.bitsConfig.server.port | default 3000 }}
    bits:
      bits:
        {{- if .Values.tikv.enabled }}
        tikv:
          endpoints:
            - {{ include "polytope-server.pdEndpoint" . | quote }}
          broker_lease_ttl_secs: 30
        {{- end }}
        internal_poll_base_url: {{ printf "http://%s-frontend.%s.svc:%d" (include "polytope-server.fullname" .) .Release.Namespace (.Values.frontend.port | int) | quote }}
        {{- with .Values.bitsConfig.bits.bits }}
        {{- range $k, $v := . }}
        {{- if and (ne $k "tikv") (ne $k "internal_poll_base_url") }}
        {{ $k }}: {{ $v | toYaml | trim }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- with .Values.bitsConfig.bits.targets }}
      targets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bitsConfig.bits.routes }}
      routes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bitsConfig.bits.checks }}
      checks:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bitsConfig.bits.transforms }}
      transforms:
        {{- toYaml . | nindent 8 }}
      {{- end }}
