apiVersion: v1
kind: Service
metadata:
  name: {{ include "polytope-server.fullname" . }}-frontend
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "polytope-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
    - name: broker
      port: {{ .Values.frontend.brokerPort }}
      targetPort: broker
      protocol: TCP
