{{- if .Values.marsWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polytope-server.fullname" . }}-mars-worker
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: mars-worker
spec:
  replicas: {{ .Values.marsWorker.replicas }}
  selector:
    matchLabels:
      {{- include "polytope-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mars-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "polytope-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mars-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mars-worker
          image: "{{ .Values.image.registry }}/mars-worker:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --broker-url
            - "http://{{ include "polytope-server.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.frontend.brokerPort }}"
          env:
            - name: RUST_LOG
              value: info
{{- end }}
