{{- if .Values.polytopeWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polytope-server.fullname" . }}-polytope-worker
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: polytope-worker
spec:
  replicas: {{ .Values.polytopeWorker.replicas }}
  selector:
    matchLabels:
      {{- include "polytope-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: polytope-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "polytope-server.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: polytope-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: polytope-worker
          image: "{{ .Values.image.registry }}/polytope-worker:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --broker-url
            - "http://{{ include "polytope-server.fullname" . }}-frontend.{{ .Release.Namespace }}.svc:{{ .Values.frontend.brokerPort }}"
            - --python
            - "{{ .Values.polytopeWorker.python }}"
            - --wrapper
            - "{{ .Values.polytopeWorker.wrapper }}"
            - --config-path
            - "{{ .Values.polytopeWorker.configPath }}"
          env:
            - name: RUST_LOG
              value: info
          volumeMounts:
            - name: polytope-config
              mountPath: /etc/polytope/
      volumes:
        - name: polytope-config
          configMap:
            name: {{ include "polytope-server.fullname" . }}-config
{{- end }}
