{{- if .Values.schedule }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polytope-server.fullname" . }}-schedule
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
data:
  schedule.xml: |
    {{- .Values.schedule | nindent 4 }}
{{- end }}
