{{- if and .Values.telemetry.enabled .Values.telemetry.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "polytope-server.fullname" . }}-frontend
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    {{- with .Values.telemetry.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "polytope-server.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  endpoints:
    - port: metrics
      interval: {{ .Values.telemetry.serviceMonitor.interval }}
      path: /metrics
{{- end }}
