{{- if .Values.tikv.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tikv-peer
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: tikv
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "polytope-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tikv
  ports:
    - name: tikv
      port: 20160
      targetPort: tikv
{{- end }}
