{{- if .Values.schedule.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Release.Name }}-schedule
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.schedule.vault.authRef | default "vault-auth" }}
  type: {{ .Values.schedule.vault.type | default "kv-v2" }}
  mount: {{ .Values.schedule.vault.mount | default "k8s_clusters" }}
  path: {{ .Values.schedule.vault.path | required "schedule.vault.path is required when vault is enabled" }}
  refreshAfter: {{ .Values.schedule.vault.refreshAfter | quote }}
  destination:
    create: true
    name: {{ .Values.schedule.secretName | required "schedule.secretName is required when vault is enabled" }}
{{- end }}
