{{- range $name, $pool := .Values.workerPools }}
{{- if $pool.deliveryConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-{{ $name }}-delivery-config
  labels:
    {{- include "polytope-server.labels" $ | nindent 4 }}
data:
  delivery.yaml: |
    {{- $cfg := deepCopy $pool.deliveryConfig }}
    {{- if and (eq (default "" $cfg.delivery_type) "bobs") (not $cfg.bobs_url) }}
    {{- $_ := set $cfg "bobs_url" (printf "%s:%d" $.Values.bobs.headlessService.name (int $.Values.bobs.service.port)) }}
    {{- end }}
    {{- toYaml $cfg | nindent 4 }}
{{- end }}
{{- end }}
