apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mars-service-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mars-service-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "polytope-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mars-service-manager
subjects:
  - kind: ServiceAccount
    name: mars-worker
    namespace: {{ .Release.Namespace }}
