{{- range $name, $pool := .Values.workerPools }}
{{- if $pool.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polytope-server.fullname" $ }}-worker-{{ $name }}-config
  labels:
    {{- include "polytope-server.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
data:
  config.yaml: |
    {{- $cfg := deepCopy $pool.config }}
    {{- if and (hasKey $cfg "delivery") (hasKey $cfg.delivery "bobs_url") }}
    {{- $_ := set $cfg.delivery "bobs_url" (include "polytope-server.bobsUrl" $) }}
    {{- end }}
    {{- toYaml $cfg | nindent 4 }}
{{- end }}
{{- if $pool.marsConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polytope-server.fullname" $ }}-worker-{{ $name }}-mars-config
  labels:
    {{- include "polytope-server.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
data:
  databases.yaml: |
    {{- toYaml $pool.marsConfig.databases | nindent 4 }}
  {{- if $pool.marsConfig.config }}
  config.yaml: |
    {{- toYaml $pool.marsConfig.config | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
